services:
  frontend:
    build:
      context: .
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-/api}
    restart: unless-stopped
    ports:
      - "8097:80"
    networks:
      - wcm-net

networks:
  wcm-net:
    external: true
